FROM centos

MAINTAINER Sonu

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat
RUN curl -O https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-8.5.40/* /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps
COPY /var/lib/jenkins/workspace/Test-Jobs/java-application/target/. /opt/tomcat/webapps

EXPOSE 80

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
